### ISSUE TITLE
팀 업무 배분 해볼까요?

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/cowork-practice2#1]
자~ 이제 팀 업무 배분 해볼까요?
- [x] : 작업 배분하기
-  [x] : introduce 작성하기

- [x] : fizzbuzz 작성하기

**Comment by seungjaepack** [comment]
이슈가 있어서 레포를 다시 만들었습니다. ;;;

**Comment by PpangPpang93** [comment]
고생 많으셨습니다. 제가 introduce를 해볼까 하는데 어떠신지요?

**Comment by seungjaepack** [comment]
네~ 진행해주세요~^^  전 fizzbuzz하고 있을게요~!

**Comment by PpangPpang93** [comment]
introduce.md / fizzuzz.py 파일 생성 및 업로드 부탁드려요!

**Comment by azureguy7** [comment]
네... 그럼, 제가 fizzbuzz.py를 해보겠습니다!

**Comment by seungjaepack** [comment]
네~ 라이언님~ 진행해 주세요~ 전 그럼 보드 생성해야겠군요 ㅎㅎ

**Comment by PpangPpang93** [comment]
https://youtu.be/x7tW5ACgs58
강사님 영상입니다!
