### ISSUE TITLE
SSAC 3조 introduce 작성하기 

### ISSUE THREAD

**Issue by PpangPpang93** [seungjaepack/cowork-practice2#3]
introduce upload list
- [x] 김대섭
- [x] 백승재 
- [x] 유혜선
- [x] 한환기

해당 내용 완료 후, request 진행 예정

**Comment by seungjaepack** [comment]
Keep going~!

**Comment by PpangPpang93** [comment]
작성 완료해서 pull request 완료했습니다. 
바쁘시겠지만 피드백 부탁드립니다 팀장님.

**Comment by seungjaepack** [comment]
well done~!
