### ISSUE TITLE
Python project_fizzbuzz

### ISSUE THREAD

**Issue by seungjaepack** [seungjaepack/cowork-practice2#4]
build fizzbuzz project 
- [x] : 주석 달기
- [x] : 3의 배수 일때 fizz 출력
- [x] : 5의 배수 일 때 buzz 출력
- [x] : 코드 실행 완료를 끝에 출력하기

**Comment by seungjaepack** [comment]
라이언님, 작업 진행 하시면서 여기다가 반영해주세요~ ^^

**Comment by azureguy7** [comment]
무언가 제가 잘못하고 있는 거 같습니다.
체크박스에 체크가 안되는데... 음...

**Comment by PpangPpang93** [comment]
이거 이슈를 작성한 사람이 체크를 할 수 있습니다. 이슈 제시를 팀장님이 만드셔서 그런거 같아요!
댓글로 달아주시면 될것 같습니다!

**Comment by seungjaepack** [comment]
작업 다하셨으면 제가 체크 할게요~ ^^

**Comment by seungjaepack** [comment]
작업하시고 pull Request 해주세요~ :)

**Comment by azureguy7** [comment]
모두 다 했습니다!

**Comment by seungjaepack** [comment]
well-done
